name: empty_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  collection: ^1.18.0
  drift: ^2.21.0
  drift_flutter: ^0.1.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  build_runner: ^2.4.13
  provider: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  yandex_mapkit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.21.0


flutter:
  uses-material-design: true

  assets:
    - assets/
